[package]
name = "u-cc"
version = "0.1.0"
authors = ["Nathan <nlincoln@intellifarms.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.3"
regex = "1.9"
clap = "2.32"

[build-dependencies]
lalrpop = "0.16.3"
